name: 'RepoDynamics ProMan'
description: 'Fully automated repository and project manager for GitHub'
author: 'Armin Ariamajd'
branding:
  icon: file-text
  color: blue

inputs:
  admin-token:
    description: A personal access token with administration access to the repository.
    required: false
    default: ""
#  package-build:
#    required: false
#    default: 'false'
#    description: |
#      Build the package and upload the builds as artifacts.
#  package-lint:
#    required: false
#    default: 'false'
#    description: |
#      Run the linting workflow.
#  package-test:
#    required: false
#    default: 'false'
#    description: |
#      Run the test workflow on package.
#  website-build:
#    required: false
#    default: ""
#    description: |
#      Whether to build the website; either 'true' or 'false'.
#  meta-sync:
#    default: report
#    required: false
#    description: |
#      The action to take when the dynamic files are out of sync with the repository meta content.
#      Selecting 'none' will disable this action.
#  hooks:
#    default: report
#    required: false
#    description: |
#      The action to take when running the workflow hooks.
#      Selecting 'none' will disable this action.
#  website-announcement:
#    required: false
#    default: ""
#    description: |
#      New announcement message to show on the website;
#      supports HTML syntax (don't forget to escape with \).
#      Set to 'null' to remove announcement.
#  website-announcement-description:
#    required: false
#    default: ""
#    description: |
#      Commit description (i.e. without type and title)
#      for the announcement commit and changelog entry.
#  first-major-release:
#    required: false
#    default: 'false'
#    description: |
#      Release the current 0.X.Y version as the first major release.

outputs:
  fail:
    value: ${{ steps.meta.outputs.fail }}
    description: Whether the workflow failed.
  run:
    value: ${{ steps.meta.outputs.run }}
    description: Whether to run subsequent jobs.
  website:
    value: ${{ steps.meta.outputs.website }}
    description: Configurations for website job.
  lint:
    value: ${{ steps.meta.outputs.lint }}
    description: Configurations for lint job.
  test:
    value: ${{ steps.meta.outputs.test }}
    description: Configurations for test job.
  build:
    value: ${{ steps.meta.outputs.build }}
    description: Configurations for build job.
  publish-testpypi:
    value: ${{ steps.meta.outputs.publish-testpypi }}
    description: Configurations for publish-testpypi job.
  test-testpypi:
    value: ${{ steps.meta.outputs.test-testpypi }}
    description: Configurations for test-testpypi job.
  publish-pypi:
    value: ${{ steps.meta.outputs.publish-pypi }}
    description: Configurations for publish-pypi job.
  test-pypi:
    value: ${{ steps.meta.outputs.test-pypi }}
    description: Configurations for test-pypi job.
  finalize:
    value: ${{ steps.meta.outputs.finalize }}
    description: Configurations for finalize job.

runs:
  using: "composite"
  steps:

    - name: 'Initialization'
      shell: bash
      run: |
        # Initialization
        # Print logo and heading
        printf "\n\n$(cat ${{github.action_path}}/logo.txt)\n"
        python "${{ github.action_path }}/heading.py" "1 Action Initialization"
        # Copy ProMan requirements file to the workspace so that it can be used by SetupPython for caching
        cp "${{ github.action_path }}/requirements.txt" .
        python "${{ github.action_path }}/heading.py" "1.1 Base Repository Checkout"

    - name: 'Repository Checkout (Base)'
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.admin-token || github.token }}
        repository: ${{ github.repository }}
        ref: ${{ github.event.repository.default_branch }}
        fetch-depth: 0
        path: repo_base
#        ref: >-
#          ${{
#            (
#              github.event_name == 'pull_request' && (
#                (
#                  github.event.pull_request.head.repo.full_name == github.repository
#                  && github.event.pull_request.head.ref
#                ) ||
#              )
#              && github.event.pull_request.head.ref
#            ) || github.ref
#          }}

    - name: 'Repository Checkout (Head)'
      shell: bash
      run: |
        # Repository Checkout (Head)
        python "${{ github.action_path }}/heading.py" "1.2 Head Repository Checkout"
    - uses: actions/checkout@v4
      with:
        repository: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name) || github.repository }}
        ref: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.ref) || github.ref }}
        fetch-depth: 0
        path: repo_head

    - name: 'Python Setup'
      shell: bash
      run: |
        # Python Setup
        python "${{ github.action_path }}/heading.py" "1.3 Python Setup"
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: 'Environment Setup'
      shell: bash
      run: |
        # Environment Setup
        python "${{ github.action_path }}/heading.py" "1.4 Environment Setup"
        echo "::group::Install Action Requirements"
        python -m pip install -r requirements.txt
        echo "::endgroup::"
        echo "::group::Install Action"
        python -m pip install ${{ github.action_path }}
        echo "::endgroup::"
        echo "::group::Display Environment"
        python -m pip list
        echo "::endgroup::"

    - name: 'Pre-commit Cache'
      shell: bash
      run: |
        # Pre-commit Cache
        python "${{ github.action_path }}/heading.py" "1.5 Cache Load"
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

    - name: 'Local Directory'
      id: local_dir
      shell: bash
      run: |
        # Local Directory
        python "${{ github.action_path }}/pathfinder.py"

    - name: 'Repo Cache (base)'
      shell: bash
      run: |
        # Repo Cache (base)
        python "${{ github.action_path }}/heading.py" "1.5 Cache Load"
    - if: ${{ steps.local_dir.outputs.local_dirpath_repo_base }}
      uses: actions/cache@v4
      with:
        path: ${{ steps.local_dir.outputs.local_dirpath_repo_base }}
        key: branch_${{ github.ref }}_local

    - name: 'Repo Cache (head)'
      shell: bash
      run: |
        # Repo Cache (head)
        python "${{ github.action_path }}/heading.py" "1.5 Cache Load"
    - if: ${{ steps.local_dir.outputs.local_dirpath_repo_head }}
      uses: actions/cache@v4
      with:
        path: ${{ steps.local_dir.outputs.local_dirpath_repo_head }}
        key: branch_${{ github.ref }}_local

    - name: 'Action'
      id: meta
      env:
        RD_PROMAN__ADMIN_TOKEN: ${{ inputs.admin-token }}
        RD_PROMAN__GITHUB_CONTEXT: ${{ toJSON(github) }}
        RD_PROMAN__PATH_REPO_BASE: repo_base
        RD_PROMAN__PATH_REPO_HEAD: repo_head
      shell: bash
      run: |
        # Action
        python -m proman
        python "${{ github.action_path }}/heading.py" "3 Action Finalization"
        python "${{ github.action_path }}/heading.py" "3.1 Report Upload"

    - name: 'Artifact Upload'
      uses: actions/upload-artifact@v4
      with:
        path: uploads
        name: Workflow Results
