name: 'RepoDynamics Meta'
description: 'Load repository metadata.'
author: 'Armin Ariamajd'
branding:
  icon: file-text
  color: blue


inputs:

  mode:
    description: |
      Whether to sync meta files.
    default: read
    required: false

  force-update:
      description: |
        One of `none`, `core` or `all` (default: none):
          - none: load entirely from cache, if no changes in metadata files are detected.
          - core: force update the core metadata, but not the cached API metadata.
          - all: force update the core metadata and the cached API metadata.
        Note that when a change is detected, the core metadata is always updated,
        but non-expired cached API metadata is only updated when `all` is selected.
      default: none
      required: false

  ref:
    description: |
      Reference (i.e. branch, tag or SHA) of the current repository to checkout, 
      i.e. the `ref` input of `actions/checkout`.
    default: ""
    required: false


outputs:

  meta:
    description: "Repository metadata as a JSON string."
    value: ${{ steps.metadata.outputs.meta }}

  diff:
    description: "Repository metadata diff as a JSON string."
    value: ${{ steps.metadata.outputs.diff }}


runs:
  using: "composite"
  steps:

    - name: 'Intro'
      shell: bash
      run: |
        # Repodynamics Meta
        printf "\n\n$(cat ${{github.action_path}}/logo.txt)\n\n\n"


    - name: 'Setup Python'
      shell: bash
      run: |
        # Setup Python
        echo -e "\033[1;30;48;2;200;120;255m 1. Setup Python  "
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'


    - name: 'Install RepoDynamics'
      shell: bash
      run: |
        # Install RepoDynamics
        echo -e "\033[1;30;48;2;200;120;255m 2. Install RepoDynamics  "
        pip install -r ${{ github.action_path }}/requirements.txt


    - name: 'Checkout Main Repository'
      shell: bash
      run: |
        # Checkout Main Repository
        rd-print "3. Checkout Main Repository" heading meta
        rd-print "checkout-ref: ${{ inputs.ref || github.ref }}" info
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
    - id: ext
      shell: bash
      env:
        RD_META_FILES__REPO: ${{ github.repository }}
        RD_META_FILES__REF: ${{ inputs.ref || github.ref }}
      run: |
        # Display Downloaded Files
        python -m repodynamics.actions meta files


    - name: 'Checkout Extension Repositories'
      shell: bash
      run: |
        # Checkout Extension Repositories
        rd-print "4. Checkout Extension Repositories" heading meta
        if [[ "${{ steps.ext.outputs.has_extensions }}" == "false" ]]; then
          rd-print "No 'extensions.json' was found; skipping." success
        fi
    - if: fromJSON(steps.ext.outputs.alt1).repo != ''
      uses: actions/checkout@v3
      with:
        repository: ${{ fromJSON(steps.ext.outputs.alt1).repo }}
        ref: ${{ fromJSON(steps.ext.outputs.alt1).ref }}
        sparse-checkout: ${{ fromJSON(steps.ext.outputs.alt1).path }}
        sparse-checkout-cone-mode: false
        path: ${{ fromJSON(steps.ext.outputs.alt1).path_dl }}
    - if: fromJSON(steps.ext.outputs.alt1).repo != ''
      shell: bash
      run: |
        # Display Downloaded Files
        python -m repodynamics.actions meta files

    - if: fromJSON(steps.ext.outputs.alt2).repo != ''
      uses: actions/checkout@v3
      with:
        repository: ${{ fromJSON(steps.ext.outputs.alt2).repo }}
        ref: ${{ fromJSON(steps.ext.outputs.alt2).ref }}
        sparse-checkout: ${{ fromJSON(steps.ext.outputs.alt2).path }}
        sparse-checkout-cone-mode: false
        path: ${{ fromJSON(steps.ext.outputs.alt2).path_dl }}
    - if: fromJSON(steps.ext.outputs.alt2).repo != ''
      shell: bash
      run: |
        # Display Downloaded Files
        python -m repodynamics.actions meta files

    - if: fromJSON(steps.ext.outputs.alt3).repo != ''
      uses: actions/checkout@v3
      with:
        repository: ${{ fromJSON(steps.ext.outputs.alt3).repo }}
        ref: ${{ fromJSON(steps.ext.outputs.alt3).ref }}
        sparse-checkout: ${{ fromJSON(steps.ext.outputs.alt3).path }}
        sparse-checkout-cone-mode: false
        path: ${{ fromJSON(steps.ext.outputs.alt3).path_dl }}
    - if: fromJSON(steps.ext.outputs.alt3).repo != ''
      shell: bash
      run: |
        # Display Downloaded Files
        python -m repodynamics.actions meta files


    - name: 'Initialize Cache'
      shell: bash
      run: |
        # Initialize Metadata Cache
        rd-print "5. Initialize Metadata Cache" heading meta
    - id: cache
      # This returns a cache-hit output, which is either 'true' or 'false' (str, not bool).
      # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action
      # https://github.com/actions/cache
      uses: actions/cache@v3
      with:
        path: |
          .local/metadata.json
          .local/metadata_api_cache.yaml
        # Cache is invalidated when metadata files are changed.
        # Ref. hashFiles: https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles
        key: >-
          metadata-${{
            hashFiles(
              'meta/data/*.yaml',
              '${{ fromJSON(steps.ext.outputs.alt1).hash_pattern }}',
              '${{ fromJSON(steps.ext.outputs.alt2).hash_pattern }}',
              '${{ fromJSON(steps.ext.outputs.alt3).hash_pattern }}'
            )
          }}
    

    - name: 'Get metadata'
      id: metadata
      env:
        RD_META__MODE: ${{ inputs.mode }}
        RD_META__CACHE_HIT: ${{ steps.cache.outputs.cache-hit == 'true' }}
        RD_META__FORCE_UPDATE: ${{ inputs.force-update }}
        RD_META__GITHUB_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        # Get Metadata
        rd-print "6. Get Metadata" heading meta
        if [[ "${{ inputs.force-update }}" == "none" && "${{ steps.cache.outputs.cache-hit }}" == "true" ]]; then
          rd-print "Force-update was not selected and a cache was found; loading metadata from cache..." info
        else
          if [[ "${{ inputs.force-update }}" != "none" ]]; then
            rd-print "Force-update was selected; installing extra dependencies..." info
          else
            rd-print "No cache was found; installing extra dependencies..." info
          fi
          pip install repodynamics[meta]
          rd-print "Calculating metadata..." info
        fi
        python -m repodynamics.actions meta
