name: 'RepoDynamics Init'
description: 'Initialize workflow runs.'
author: 'Armin Ariamajd'
branding:
  icon: file-text
  color: blue

inputs:

  admin-token:
    description: A personal access token with administration access to the repository.
    required: false
    default: ""
  package-build:
    required: false
    default: 'false'
    description: |
      Build the package and upload the builds as artifacts.
  package-lint:
    required: false
    default: 'false'
    description: |
      Run the linting workflow.
  package-test:
    required: false
    default: 'false'
    description: |
      Run the test workflow on package.
  website-build:
    required: false
    default: ""
    description: |
      Whether to build the website; either 'true' or 'false'.
  meta-sync:
    default: report
    required: false
    description: |
      The action to take when the dynamic files are out of sync with the repository meta content.
      Selecting 'none' will disable this action.
  hooks:
    default: report
    required: false
    description: |
      The action to take when running the workflow hooks.
      Selecting 'none' will disable this action.
  website-announcement:
    required: false
    default: ""
    description: |
      New announcement message to show on the website; 
      supports HTML syntax (don't forget to escape with \).
      Set to 'null' to remove announcement.
  website-announcement-description:
    required: false
    default: ""
    description: |
      Commit description (i.e. without type and title) 
      for the announcement commit and changelog entry.

outputs:

  config:
    description: Configurations for subsequent workflow jobs.
    value: ${{ steps.meta.outputs.config }}

  metadata-ci:
    description: Metadata for subsequent workflow jobs.
    value: ${{ steps.meta.outputs.metadata-ci }}


runs:
  using: "composite"
  steps:

    - name: 'Initialize'
      shell: bash
      run: |
        # Initialize
        printf "\n\n$(cat ${{github.action_path}}/logo.txt)\n\n\n"
        python "${{ github.action_path }}/heading.py" "1" "Checkout Repository"

    - name: 'Checkout Repository'
      uses: actions/checkout@v3
      with:
        repository: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name) || github.repository }}
        ref: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.ref) || github.ref }}
        fetch-depth: 0
        path: repo1

    - id: setup_env
      shell: bash
      run: |
        # Setup Environment
        python "${{ github.action_path }}/heading.py" "1" "Setup Environment"
        echo "::group::Load requirements file"
        python "${{ github.action_path }}/pathfinder.py" "${{ github.action_path }}"
        echo "::endgroup::"

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: ${{ steps.setup_env.outputs.path_requirements }}

    - shell: bash
      run: |
        # Install RepoDynamics
        python "${{ github.action_path }}/heading.py" "2" "Install RepoDynamics"
        echo "::group::Install Dependencies"
        python -m pip install -r ${{ steps.setup_env.outputs.path_requirements }}
        echo "::endgroup::"
        echo "::group::Display pip environment"
        python -m pip list
        echo "::endgroup::"
        rd-print "h2" "Load Cache"

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: >-
          pre-commit-3
            -${{ env.pythonLocation }}
            -${{ 
              hashFiles(
                '.github/.pre-commit-config.yaml', 
                '${{ steps.setup_env.outputs.path_requirements }}'
              ) 
            }}

    - name: 'Run'
      id: meta
      env:
        RD_INIT__CONTEXT: ${{ toJson(github) }}
        RD_INIT__ADMIN_TOKEN: ${{ inputs.admin-token }}
        RD_INIT__PACKAGE_BUILD: ${{ inputs.package-build }}
        RD_INIT__PACKAGE_LINT: ${{ inputs.package-lint }}
        RD_INIT__PACKAGE_TEST: ${{ inputs.package-test }}
        RD_INIT__WEBSITE_BUILD: ${{ inputs.website-build }}
        RD_INIT__META_SYNC: ${{ inputs.meta-sync }}
        RD_INIT__HOOKS: ${{ inputs.hooks }}
        RD_INIT__WEBSITE_ANNOUNCEMENT: ${{ inputs.website-announcement }}
        RD_INIT__WEBSITE_ANNOUNCEMENT_MSG: ${{ inputs.website-announcement-description }}
      shell: bash
      run: |
        # Run Action
        rd-print "h1" "Initialize RepoDynamics"
        python -m repodynamics.actions init

    - name: 'Checkout Repository'
      if: fromJSON(steps.meta.outputs.internal).finit
      uses: actions/checkout@v3
      with:
        repository: ${{ fromJSON(steps.meta.outputs.internal).repository }}
        ref: ${{ fromJSON(steps.meta.outputs.internal).ref }}
        fetch-depth: 0

    - name: 'Run'
      if: fromJSON(steps.meta.outputs.internal).finit
      id: finit
      env:
        RD_INIT__CONTEXT: ${{ toJson(github) }}
        RD_INIT__ADMIN_TOKEN: ${{ inputs.admin-token }}
      shell: bash
      run: |
        # Run Action
        rd-print "h1" "Finalize RepoDynamics"
        python -m repodynamics.actions finit

    - name: 'Upload log as artifact'
      uses: actions/upload-artifact@v3
      with:
        path: |
          ${{ steps.meta.outputs.path-log }}
        name: Workflow Details

