
[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"


# ----------------------------------------- setuptools -------------------------------------------
[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true


# ----------------------------------------- Project Metadata -------------------------------------
#
[project]
version = "0.0.0.dev6"
name = "ProMan"
dependencies = [
    "pre-commit == 3.8.0",
    "ActionMan",
    "ControlMan == 0.0.0.dev274",
    "ConventionalCommits == 0.0.0.dev7",
    "GitHub-Contexts",
    "LoggerMan == 0.0.0.dev19",
    "MDit == 0.0.0.dev8",
    "HTMP == 0.0.0.dev5",
    "PyLinks",
    "PySyntax",
    "VersionMan",
    "GitTidy == 0.0.0.dev11",
    "PkgData",
    "PyShellMan",
    "PySerials == 0.0.0.dev11",
    "FileEx",
    "ANSI-SGR",
]
requires-python = ">=3.10"


#[project.scripts]
#rd-print = "repodynamics.actions._print:main"
#repodynamics-get-metadata = "pypackit.metadata:__main__"
#repodynamics-sync-files = "pypackit.templates:__main__"
#repodynamics-deploy = "pypackit.cd:__main__"